server:
  port: 8082
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql:///leyou
    password: root
    username: root
    hikari:
      max-lifetime: 28830000
      maximum-pool-size: 9
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
mybatis:
  type-aliases-package: com.leyou.item.pojo